# Data cleaning

In [16]:
import pandas as pd
import numpy as np

In [17]:
raw_data_path = r".\Data\collegeplayer_cleaned.csv"
raw_data = pd.read_csv(raw_data_path)
raw_data.head()

,Unnamed: 0,player_name,TEAM,AFFILIATION,YEAR,ROUND,ROUND.1,OVERALL,team,conf,...,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,Unnamed: 64,Unnamed: 65
0,0,Cade Cunningham,Detroit Pistons,Oklahoma State,2021.0,1,1,1,Oklahoma St.,B12,...,2.53637,0.7037,5.4815,6.1852,3.4444,1.5926,0.7778,20.2222,Wing F,8.87260
1,1,Evan Mobley,Cleveland Cavaliers,Southern California,2021.0,1,3,3,USC,P12,...,5.25248,2.7273,5.9394,8.6667,2.3939,0.7879,2.8485,16.3636,C,2.10197
2,2,Scottie Barnes,Toronto Raptors,Florida State,2021.0,1,4,4,Florida St.,ACC,...,2.99510,1.4583,2.5417,4.0000,4.0833,1.4583,0.4583,10.3333,Scoring PG,3.85045
3,3,Jalen Suggs,Orlando Magic,Gonzaga,2021.0,1,5,5,Gonzaga,WCC,...,4.11123,0.6000,4.7333,5.3333,4.5333,1.9000,0.3333,14.3000,Combo G,6.42283
4,4,Franz Wagner,Orlando Magic,Michigan,2021.0,1,8,8,Michigan,B10,...,3.05480,0.8889,4.7037,5.5926,1.0000,1.2593,0.5926,11.5556,Wing F,9.22711

## Delete useless data

In [18]:
delet_index = [0, 2, 3, 5, 6, 8, 9, 32, 33, 34, 35, 36,
               37, 38, 39, 40, 41, 66, 67, 68, 69, 70, 71, 72]
drop_list = []
for index in delet_index:
    drop_list.append(raw_data.columns[index])
print(drop_list)

['Unnamed: 0', 'TEAM', 'AFFILIATION', 'ROUND', 'ROUND.1', 'team', 'conf', 'yr', 'ht', 'num', 'porpag', 'adjoe', 'pfr', 'year', 'pid', 'type', 'Rec Rank', 'treb', 'ast', 'stl', 'blk', 'pts', 'Unnamed: 64', 'Unnamed: 65']

In [34]:
data_cleaned = raw_data.drop(columns=drop_list)
# data_test_drop = raw_data.drop(index=[0, 1], axis=0)
data_cleaned.head()
# data_test_drop.head()

# print(len(data_cleaned))
# print(data_cleaned['player_name'][1])

,player_name,YEAR,OVERALL,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,...,stops,bpm,obpm,dbpm,gbpm,mp,ogbpm,dgbpm,oreb,dreb
0,Cade Cunningham,2021.0,1,27,78.0,104.1,28.6,51.6,57.46,2.3,...,207.722,6.28955,3.19980,3.08975,7.41636,35.4074,4.87999,2.53637,0.7037,5.4815
1,Evan Mobley,2021.0,3,33,83.6,119.4,23.4,59.5,62.40,9.7,...,256.359,13.00120,5.53482,7.46638,12.64050,33.9394,7.38800,5.25248,2.7273,5.9394
2,Scottie Barnes,2021.0,4,24,58.9,107.5,25.3,53.1,54.78,7.4,...,119.770,8.27087,4.94571,3.32516,7.19008,24.7917,4.19499,2.99510,1.4583,2.5417
3,Jalen Suggs,2021.0,5,30,67.5,110.4,25.3,55.9,59.39,2.7,...,209.261,9.32632,4.85317,4.47315,8.48340,28.9333,4.37217,4.11123,0.6000,4.7333
4,Franz Wagner,2021.0,8,27,66.1,105.5,18.6,53.4,56.59,3.4,...,171.133,5.85695,2.63123,3.22572,5.45181,30.7407,2.39701,3.05480,0.8889,4.7037

## Delete repeated data

In [64]:
index_list = []

for i in range(len(data_cleaned)-1):
    if data_cleaned['player_name'][i] == data_cleaned['player_name'][i+1]:
        index_list.append(i)

new_data_cleaned = data_cleaned.drop(index=index_list, axis=0)
new_data_cleaned = new_data_cleaned.reset_index(drop=True) # 重新排序
new_data_cleaned

,player_name,YEAR,OVERALL,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,...,stops,bpm,obpm,dbpm,gbpm,mp,ogbpm,dgbpm,oreb,dreb
0,Cade Cunningham,2021.0,1,27,78.0,104.1,28.6,51.6,57.46,2.3,...,207.722,6.28955,3.19980,3.089750,7.41636,35.4074,4.87999,2.536370,0.7037,5.4815
1,Evan Mobley,2021.0,3,33,83.6,119.4,23.4,59.5,62.40,9.7,...,256.359,13.00120,5.53482,7.466380,12.64050,33.9394,7.38800,5.252480,2.7273,5.9394
2,Scottie Barnes,2021.0,4,24,58.9,107.5,25.3,53.1,54.78,7.4,...,119.770,8.27087,4.94571,3.325160,7.19008,24.7917,4.19499,2.995100,1.4583,2.5417
3,Jalen Suggs,2021.0,5,30,67.5,110.4,25.3,55.9,59.39,2.7,...,209.261,9.32632,4.85317,4.473150,8.48340,28.9333,4.37217,4.111230,0.6000,4.7333
4,Franz Wagner,2021.0,8,28,78.8,119.5,19.4,54.4,58.65,2.9,...,201.179,11.31880,5.41689,5.901900,10.60920,31.6786,5.27693,5.332290,0.7143,5.8214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,Patty Mills,2009.0,55,24,61.7,108.8,29.0,47.6,52.27,1.6,...,143.825,5.16627,4.90741,0.258865,7.47588,33.9583,5.28972,2.186160,0.4583,1.8333
591,Ahmad Nivins,2009.0,56,32,96.5,119.7,22.9,61.2,66.99,12.5,...,261.974,5.55748,3.18525,2.372230,6.58919,39.3438,5.69052,0.898667,3.9375,7.8750
592,Lester Hudson,2009.0,58,30,90.6,115.3,35.5,51.7,56.00,6.5,...,247.094,9.11737,7.93000,1.187370,11.58180,36.5333,10.44650,1.135300,2.2000,5.8667
593,Chinemelu Elonu,2009.0,59,33,59.1,112.0,20.4,66.3,65.87,13.8,...,165.533,5.16497,2.36602,2.798950,5.17411,23.7273,3.16663,2.007480,2.7879,4.4242
594,Robert Dozier,2009.0,60,37,75.3,114.4,21.0,55.2,59.37,10.7,...,245.353,10.39380,3.86323,6.530560,8.84328,30.2162,4.24030,4.602980,2.8649,4.5946

## classify every 5 players in a group

In [65]:
label_list = []

for i in range(len(new_data_cleaned)):
    for j in range(12):
        if (new_data_cleaned['OVERALL'][i]>5*j) & (new_data_cleaned['OVERALL'][i]<=5*j+5):
            label_list.append(j+1)
            
print(label_list)

[1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10, 11, 11, 11, 12, 12, 12, 12, 12, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 7, 7, 7, 8, 8, 9, 9, 3, 9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 12, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 9, 9, 10, 10, 10, 11, 11, 11, 12, 12, 12, 12, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 11, 11, 11, 12, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 10, 10, 10, 10, 10, 11, 12, 12, 12, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5, 5, 5, 5, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 10, 10, 10, 11, 11, 12, 12, 12, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 12, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 10, 10, 10, 11, 11, 11, 12, 12, 12, 12]

In [66]:
new_data_cleaned['label'] = label_list
# new_data_cleaned

new_data_cleaned.to_csv('./NCAA_data_cleaned.csv', index=False)

,player_name,YEAR,OVERALL,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,...,bpm,obpm,dbpm,gbpm,mp,ogbpm,dgbpm,oreb,dreb,label
0,Cade Cunningham,2021.0,1,27,78.0,104.1,28.6,51.6,57.46,2.3,...,6.28955,3.19980,3.089750,7.41636,35.4074,4.87999,2.536370,0.7037,5.4815,1
1,Evan Mobley,2021.0,3,33,83.6,119.4,23.4,59.5,62.40,9.7,...,13.00120,5.53482,7.466380,12.64050,33.9394,7.38800,5.252480,2.7273,5.9394,1
2,Scottie Barnes,2021.0,4,24,58.9,107.5,25.3,53.1,54.78,7.4,...,8.27087,4.94571,3.325160,7.19008,24.7917,4.19499,2.995100,1.4583,2.5417,1
3,Jalen Suggs,2021.0,5,30,67.5,110.4,25.3,55.9,59.39,2.7,...,9.32632,4.85317,4.473150,8.48340,28.9333,4.37217,4.111230,0.6000,4.7333,1
4,Franz Wagner,2021.0,8,28,78.8,119.5,19.4,54.4,58.65,2.9,...,11.31880,5.41689,5.901900,10.60920,31.6786,5.27693,5.332290,0.7143,5.8214,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,Patty Mills,2009.0,55,24,61.7,108.8,29.0,47.6,52.27,1.6,...,5.16627,4.90741,0.258865,7.47588,33.9583,5.28972,2.186160,0.4583,1.8333,11
591,Ahmad Nivins,2009.0,56,32,96.5,119.7,22.9,61.2,66.99,12.5,...,5.55748,3.18525,2.372230,6.58919,39.3438,5.69052,0.898667,3.9375,7.8750,12
592,Lester Hudson,2009.0,58,30,90.6,115.3,35.5,51.7,56.00,6.5,...,9.11737,7.93000,1.187370,11.58180,36.5333,10.44650,1.135300,2.2000,5.8667,12
593,Chinemelu Elonu,2009.0,59,33,59.1,112.0,20.4,66.3,65.87,13.8,...,5.16497,2.36602,2.798950,5.17411,23.7273,3.16663,2.007480,2.7879,4.4242,12
594,Robert Dozier,2009.0,60,37,75.3,114.4,21.0,55.2,59.37,10.7,...,10.39380,3.86323,6.530560,8.84328,30.2162,4.24030,4.602980,2.8649,4.5946,12

## delet invalid data

In [6]:
# delet_index = [2, 3, 5, 6, 8, 9, 32, 33, 34, 35, 36,
#                37, 38, 39, 40, 41, 66, 67, 68, 69,
#                70, 71, 72]
# data_cleaned = np.delete(raw_data_np, delet_index, axis=1)
# print(data_cleaned[:15, :10])
# print(data_cleaned.shape)
# print(data_cleaned.shape[1])

In [7]:
# new_data_cleaned = np.zeros(shape=[1, data_cleaned.shape[1]])

# for i in range(data_cleaned.shape[0]-1):
#     if data_cleaned[i][1] != data_cleaned[i+1][1]:
#         new_data_cleaned = np.vstack((new_data_cleaned, data_cleaned[i]))

# new_data_cleaned = np.vstack((new_data_cleaned, data_cleaned[-1]))
# new_data_cleaned = new_data_cleaned[1:]
# print(new_data_cleaned[-5:, :10])
# print(new_data_cleaned.shape)
# print(new_data_cleaned[:10, 3])

## classify player in years

In [8]:
# year_list = [2021.0, 2020.0, 2019.0, 2018.0, 2017.0, 2016.0, 2015.0,
#              2014.0, 2013.0, 2012.0, 2011.0, 2010.0, 2009.0]

# # axis=0 : year ; axis=1 : player ; axis=2 : data
# player_in_year = np.zeros(shape=[len(year_list), 1, 51])
# print(player_in_year.shape)

In [9]:
# for i in range(data_cleaned.shape[0]):
#     for j in range(len(year_list)):
#         if data_cleaned[i][2] == year_list[j]:
#             data_expend_dim = np.expand_dims(data_cleaned[i], 0)
#             print(data_expend_dim.shape)
#             print(player_in_year[j].shape)
#             player_in_year[j] = np.vstack((player_in_year[j], data_expend_dim))
            
# print(player_in_year.shape)

## classify every 5 players in draft picks

In [10]:
# picks_label = np.zeros(shape=[new_data_cleaned.shape[0]])
# # print(picks_label.shape)
# for i in range(new_data_cleaned.shape[0]):
# # for i in range(15):
#     if (new_data_cleaned[i][3]>=1) & (new_data_cleaned[i][3]<=5):
#         picks_label[i] = 1
#     elif (new_data_cleaned[i][3]>=6) & (new_data_cleaned[i][3]<=10):
#         picks_label[i] = 2
#     elif (new_data_cleaned[i][3]>=11) & (new_data_cleaned[i][3]<=15):
#         picks_label[i] = 3
#     elif (new_data_cleaned[i][3]>=16) & (new_data_cleaned[i][3]<=20):
#         picks_label[i] = 4
#     elif (new_data_cleaned[i][3]>=21) & (new_data_cleaned[i][3]<=25):
#         picks_label[i] = 5
#     elif (new_data_cleaned[i][3]>=26) & (new_data_cleaned[i][3]<=30):
#         picks_label[i] = 6
#     elif (new_data_cleaned[i][3]>=31) & (new_data_cleaned[i][3]<=35):
#         picks_label[i] = 7
#     elif (new_data_cleaned[i][3]>=36) & (new_data_cleaned[i][3]<=40):
#         picks_label[i] = 8
#     elif (new_data_cleaned[i][3]>=41) & (new_data_cleaned[i][3]<=45):
#         picks_label[i] = 9
#     elif (new_data_cleaned[i][3]>=46) & (new_data_cleaned[i][3]<=50):
#         picks_label[i] = 10
#     elif (new_data_cleaned[i][3]>=51) & (new_data_cleaned[i][3]<=55):
#         picks_label[i] = 11
#     else:
#         picks_label[i] = 12

# print(new_data_cleaned[:15, 3])
# print(picks_label[:15])
# print(picks_label)

In [11]:
# picks_label_expand = np.expand_dims(picks_label, 1)
# new_data_clean_label = np.concatenate([new_data_cleaned, picks_label_expand], axis=1)
# print(new_data_clean_label.shape)
# print(new_data_clean_label)

# save_path = r'./NCAA_player_data.npy'
# np.save(save_path, new_data_clean_label)

## save numpy as csv

In [12]:
# import csv

In [13]:
# header_file_path = r"C:\Users\dzr77\Desktop\NBA_data.txt"
# header_file = np.loadtxt(header_file_path, dtype='str', delimiter=',')
# # print(header_file)

# header_list = header_file.tolist()
# header_list.append('label')
# # print(header_list)

# playerList = new_data_clean_label.tolist()
# print(playerList)

In [14]:
# # 创建一个DataFrame对象
# data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'Gender': ['F', 'M', 'M']}
# df = pd.DataFrame(data)

# # 将DataFrame对象保存为CSV文件
# df.to_csv('data.csv', index=False)

In [15]:
# with open('./data_cleaned.csv', 'w', encoding='utf-8', newline='') as f:
#     write = csv.DictWriter(f, fieldnames=header_list)
#     write.writeheader()
#     for data in playerList:
#         write.writerow(data)