In [14]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import plot_confusion_matrix, accuracy_score, precision_score, mean_squared_error
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.impute import SimpleImputer
from sklearn.ensemble import AdaBoostClassifier

In [2]:
raw_data_path = r".\dataset\collegeplayer_cleaned.csv"
raw_data = pd.read_csv(raw_data_path)
raw_data.head()

,Unnamed: 0,player_name,TEAM,AFFILIATION,YEAR,ROUND,ROUND.1,OVERALL,team,conf,...,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,Unnamed: 64,Unnamed: 65
0,0,Cade Cunningham,Detroit Pistons,Oklahoma State,2021.0,1,1,1,Oklahoma St.,B12,...,2.53637,0.7037,5.4815,6.1852,3.4444,1.5926,0.7778,20.2222,Wing F,8.87260
1,1,Evan Mobley,Cleveland Cavaliers,Southern California,2021.0,1,3,3,USC,P12,...,5.25248,2.7273,5.9394,8.6667,2.3939,0.7879,2.8485,16.3636,C,2.10197
2,2,Scottie Barnes,Toronto Raptors,Florida State,2021.0,1,4,4,Florida St.,ACC,...,2.99510,1.4583,2.5417,4.0000,4.0833,1.4583,0.4583,10.3333,Scoring PG,3.85045
3,3,Jalen Suggs,Orlando Magic,Gonzaga,2021.0,1,5,5,Gonzaga,WCC,...,4.11123,0.6000,4.7333,5.3333,4.5333,1.9000,0.3333,14.3000,Combo G,6.42283
4,4,Franz Wagner,Orlando Magic,Michigan,2021.0,1,8,8,Michigan,B10,...,3.05480,0.8889,4.7037,5.5926,1.0000,1.2593,0.5926,11.5556,Wing F,9.22711

In [3]:
index_list = []

for i in range(len(raw_data)-1):
    if raw_data['player_name'][i] == raw_data['player_name'][i+1]:
        index_list.append(i)

new_data = raw_data.drop(index=index_list, axis=0)
new_data = new_data.reset_index(drop=True) # 重新排序
new_data

,Unnamed: 0,player_name,TEAM,AFFILIATION,YEAR,ROUND,ROUND.1,OVERALL,team,conf,...,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,Unnamed: 64,Unnamed: 65
0,0,Cade Cunningham,Detroit Pistons,Oklahoma State,2021.0,1,1,1,Oklahoma St.,B12,...,2.536370,0.7037,5.4815,6.1852,3.4444,1.5926,0.7778,20.2222,Wing F,8.872600
1,1,Evan Mobley,Cleveland Cavaliers,Southern California,2021.0,1,3,3,USC,P12,...,5.252480,2.7273,5.9394,8.6667,2.3939,0.7879,2.8485,16.3636,C,2.101970
2,2,Scottie Barnes,Toronto Raptors,Florida State,2021.0,1,4,4,Florida St.,ACC,...,2.995100,1.4583,2.5417,4.0000,4.0833,1.4583,0.4583,10.3333,Scoring PG,3.850450
3,3,Jalen Suggs,Orlando Magic,Gonzaga,2021.0,1,5,5,Gonzaga,WCC,...,4.111230,0.6000,4.7333,5.3333,4.5333,1.9000,0.3333,14.3000,Combo G,6.422830
4,5,Franz Wagner,Orlando Magic,Michigan,2021.0,1,8,8,Michigan,B10,...,5.332290,0.7143,5.8214,6.5357,3.0000,1.2500,1.0357,12.4643,Wing F,6.880850
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,1482,Patty Mills,Portland Trail Blazers,St. Mary's (CA),2009.0,2,25,55,Saint Mary's,WCC,...,2.186160,0.4583,1.8333,2.2917,3.7917,2.2083,0.2083,18.6250,NaN,14.264300
591,1483,Ahmad Nivins,Dallas Mavericks,Saint Joseph's,2009.0,2,26,56,Saint Joseph's,A10,...,0.898667,3.9375,7.8750,11.8125,1.0000,0.8125,1.7500,19.1562,NaN,0.048109
592,1484,Lester Hudson,Boston Celtics,Tennessee-Martin,2009.0,2,28,58,Tennessee Martin,OVC,...,1.135300,2.2000,5.8667,8.0667,4.1333,2.1000,0.6000,27.7333,NaN,14.790600
593,1485,Chinemelu Elonu,Los Angeles Lakers,Texas A&M,2009.0,2,29,59,Texas A&M,B12,...,2.007480,2.7879,4.4242,7.2121,0.3030,0.3030,1.5758,9.7273,NaN,0.000000
594,1486,Robert Dozier,Miami Heat,Memphis,2009.0,2,30,60,Memphis,CUSA,...,4.602980,2.8649,4.5946,7.4595,1.4324,1.2703,1.6486,12.8919,NaN,2.898930

In [6]:
delet_index = [0, 2, 3, 6, 8, 9, 10, 32, 33, 34, 35, 36,
               37, 38, 39, 40, 71, 72]
drop_list = []

for index in delet_index:
    drop_list.append(raw_data.columns[index])
    
print(drop_list)

['Unnamed: 0', 'TEAM', 'AFFILIATION', 'ROUND.1', 'team', 'conf', 'GP', 'yr', 'ht', 'num', 'porpag', 'adjoe', 'pfr', 'year', 'pid', 'type', 'Unnamed: 64', 'Unnamed: 65']

In [11]:
new_data_cleaned = new_data.drop(columns=drop_list)
new_data_cleaned

,player_name,YEAR,ROUND,OVERALL,Min_per,Ortg,usg,eFG,TS_per,ORB_per,...,mp,ogbpm,dgbpm,oreb,dreb,treb,ast,stl,blk,pts
0,Cade Cunningham,2021.0,1,1,78.0,104.1,28.6,51.6,57.46,2.3,...,35.4074,4.87999,2.536370,0.7037,5.4815,6.1852,3.4444,1.5926,0.7778,20.2222
1,Evan Mobley,2021.0,1,3,83.6,119.4,23.4,59.5,62.40,9.7,...,33.9394,7.38800,5.252480,2.7273,5.9394,8.6667,2.3939,0.7879,2.8485,16.3636
2,Scottie Barnes,2021.0,1,4,58.9,107.5,25.3,53.1,54.78,7.4,...,24.7917,4.19499,2.995100,1.4583,2.5417,4.0000,4.0833,1.4583,0.4583,10.3333
3,Jalen Suggs,2021.0,1,5,67.5,110.4,25.3,55.9,59.39,2.7,...,28.9333,4.37217,4.111230,0.6000,4.7333,5.3333,4.5333,1.9000,0.3333,14.3000
4,Franz Wagner,2021.0,1,8,78.8,119.5,19.4,54.4,58.65,2.9,...,31.6786,5.27693,5.332290,0.7143,5.8214,6.5357,3.0000,1.2500,1.0357,12.4643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,Patty Mills,2009.0,2,55,61.7,108.8,29.0,47.6,52.27,1.6,...,33.9583,5.28972,2.186160,0.4583,1.8333,2.2917,3.7917,2.2083,0.2083,18.6250
591,Ahmad Nivins,2009.0,2,56,96.5,119.7,22.9,61.2,66.99,12.5,...,39.3438,5.69052,0.898667,3.9375,7.8750,11.8125,1.0000,0.8125,1.7500,19.1562
592,Lester Hudson,2009.0,2,58,90.6,115.3,35.5,51.7,56.00,6.5,...,36.5333,10.44650,1.135300,2.2000,5.8667,8.0667,4.1333,2.1000,0.6000,27.7333
593,Chinemelu Elonu,2009.0,2,59,59.1,112.0,20.4,66.3,65.87,13.8,...,23.7273,3.16663,2.007480,2.7879,4.4242,7.2121,0.3030,0.3030,1.5758,9.7273
594,Robert Dozier,2009.0,2,60,75.3,114.4,21.0,55.2,59.37,10.7,...,30.2162,4.24030,4.602980,2.8649,4.5946,7.4595,1.4324,1.2703,1.6486,12.8919

## impute missing data

In [12]:
new_data_cleaned.drop(columns=['player_name', 'YEAR', 'OVERALL'], inplace=True)
new_data_cleaned

,ROUND,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,...,mp,ogbpm,dgbpm,oreb,dreb,treb,ast,stl,blk,pts
0,1,78.0,104.1,28.6,51.6,57.46,2.3,16.2,20.2,22.0,...,35.4074,4.87999,2.536370,0.7037,5.4815,6.1852,3.4444,1.5926,0.7778,20.2222
1,1,83.6,119.4,23.4,59.5,62.40,9.7,18.8,14.1,16.6,...,33.9394,7.38800,5.252480,2.7273,5.9394,8.6667,2.3939,0.7879,2.8485,16.3636
2,1,58.9,107.5,25.3,53.1,54.78,7.4,11.0,31.6,22.4,...,24.7917,4.19499,2.995100,1.4583,2.5417,4.0000,4.0833,1.4583,0.4583,10.3333
3,1,67.5,110.4,25.3,55.9,59.39,2.7,18.0,23.7,21.5,...,28.9333,4.37217,4.111230,0.6000,4.7333,5.3333,4.5333,1.9000,0.3333,14.3000
4,1,78.8,119.5,19.4,54.4,58.65,2.9,19.6,17.4,12.5,...,31.6786,5.27693,5.332290,0.7143,5.8214,6.5357,3.0000,1.2500,1.0357,12.4643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,2,61.7,108.8,29.0,47.6,52.27,1.6,6.0,25.9,17.1,...,33.9583,5.28972,2.186160,0.4583,1.8333,2.2917,3.7917,2.2083,0.2083,18.6250
591,2,96.5,119.7,22.9,61.2,66.99,12.5,22.6,6.1,18.3,...,39.3438,5.69052,0.898667,3.9375,7.8750,11.8125,1.0000,0.8125,1.7500,19.1562
592,2,90.6,115.3,35.5,51.7,56.00,6.5,18.3,27.3,15.0,...,36.5333,10.44650,1.135300,2.2000,5.8667,8.0667,4.1333,2.1000,0.6000,27.7333
593,2,59.1,112.0,20.4,66.3,65.87,13.8,21.5,2.9,22.9,...,23.7273,3.16663,2.007480,2.7879,4.4242,7.2121,0.3030,0.3030,1.5758,9.7273
594,2,75.3,114.4,21.0,55.2,59.37,10.7,16.5,9.3,18.2,...,30.2162,4.24030,4.602980,2.8649,4.5946,7.4595,1.4324,1.2703,1.6486,12.8919

In [15]:
# Filling missing data
si = SimpleImputer(strategy='median')
new_data_cleaned_imputed = si.fit_transform(new_data_cleaned)
print(new_data_cleaned_imputed.shape)
np.save('./NCAA_data_cleaned_imputed_twoclass.npy', new_data_cleaned_imputed)

(595, 52)

In [16]:
array_2021 = new_data_cleaned_imputed[:48, :]
array_rest = new_data_cleaned_imputed[48:, :]
# print(array_2021.shape)
# print(array_rest.shape)
np.save('./data_2021_twoclass.npy', array_2021)
np.save('./data_rest_twoclass.npy', array_rest)

(48, 52)
(547, 52)